version: '3.7'

services:
  ghpage:
    build:
      context: .
    image: mendhak/jekyll-site
    command: "bundle exec jekyll serve --config _config.yml --host 0.0.0.0 --drafts --incremental --force_polling"
    volumes:
      - ./:/srv/jekyll
    ports:
      - "0.0.0.0:4000:4000"